Repository gisce/destral, pull requests merged in 2018-07, with the labels that each got.

#110 Check if the module is already intalled
  destral/openerp.py
Labels: enhancement

#111 Add new class OOTestWithCursor
  destral/testing.py
  docs/README.rst
  docs/how-to.rst
  docs/index.rst
Labels: feature

#112 Fix cursor getting on OOTestCaseWithCursor
  destral/testing.py
Labels: bug, enhancement
